### PR TITLE
UTF-8 encoding problem solved for excel on mac.

### PR DESCRIPTION
**Pull request by punknroll**
There is an encoding problem if you want to open files in excel on a mac. 

http://stackoverflow.com/questions/4348802/how-can-i-output-a-utf-8-csv-in-php-that-excel-will-read-properly

This fix works. You can open it in excel an a mac now too.

### CODE REVIEW

**Comment by punknroll** [comment]
Sorry, I got no notification. I will take a look at your asked modifications asap.

cheers

**Comment by punknroll** [comment]
Hi, now I made the required modifications. Sorry for my late reply.

Cheers

**Comment by brookinsconsulting** [comment]
Hello @punknroll 

Thank you for coming back and addressing our comments! 

I'm sure these improvements will help others.

Thank you for your contributions!

Cheers,
Brookins Consulting

**Comment by punknroll** [comment]
I am glad I could contribute to your work!

Cheers,

**Comment by brookinsconsulting** [comment]
Hello @punknroll 

I'm sorry to say that after a lot of negative issue reports from users and a lot of consideration we have reverted the changes you introduced into this PR and re-introduced pure utf8 encoded export output by default.

We talk a little about why chasing double click report opening support in general with non-free document readers is a bad idea here, https://github.com/brookinsconsulting/bccie/issues/12#issuecomment-74237903

After a lot of thought we have refactored bccie to use a handler system for the export formatting output.
 
https://github.com/brookinsconsulting/bccie/commit/ee1e7add576ea8310c57043dfb369ea5ec8a5ee0

This system can be extended and customized as desired / required.

We implemented a handler containing the changes you introduced within this PR into the utf16le handler which you can use if you still need this feature by modifying the cie.ini setting 'ExportOutputFormatHandlerDefault'.

https://github.com/brookinsconsulting/bccie/blob/master/classes/exportFormatOutputHandlers/bccieExportFormatOutputHandlerUtf16Le.php

https://github.com/brookinsconsulting/bccie/blob/ee1e7add576ea8310c57043dfb369ea5ec8a5ee0/settings/cie.ini.append.php#L67

I hope you can understand why this was done since most users had serious problems with the changes introduced by default by this PR.

Cheers,
Brookins Consulting

**Comment by punknroll** [comment]
Hello @brookinsconsulting,

I am sorry to hear that my PR caused some trouble. I think the utf16le handler is a good solution.

Cheers,

**Pull request merged**
